spring:
  profiles:
    active: prod
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o892eutomay3940o.mysql.rds.aliyuncs.com:3306/test?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false
    username: mzdb
    password: MOziDB2018
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true





