spring:
  profiles:
    active: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.203:3306/test
    username: root
    password: sz73go
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true





