server:
  port: 11111

management:
  security:
    enabled: false

spring:
  redis:
    database: 0
    host: 47.99.114.23
    password: 7c4a8d09ik0g4
    port: 6379
    timeout: 0

kafka:
  broker:
    address: 47.99.114.23:9092
  zookeeper:
    connect: 47.99.114.23:2181
  topic: mozi-kafka
  messageKey: tramy.key
  partition: 0
  group: client-group

#mq配置
com:
  mqtt:
    host: tcp://127.0.0.1:1883
    clientId: myself_mqtt_demo
    userName: wpw
    passWord: 123456
    subscribeTopic: s2c/+
    publishTopic: c2s/100120201100001C
    timeout: 10
    keepAlive: 90
    maxInfLight: 1000000



