spring:
  application:
    name: redis
  jpa:
    database: mysql
    show-sql: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-bp1o892eutomay3940o.mysql.rds.aliyuncs.com:3306/oa_db?characterEncoding=utf8
    username: mzdb
    password: MOziDB2018

  # 配置Redis的连接密码
  redis:
    host: 47.99.114.23
    password: 7c4a8d09ik0g4
    database: 7
    port: 6379